services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${DATA_DIR}:/data:rw
    network_mode: host
    restart: unless-stopped
