services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}:/data
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media
    restart: unless-stopped
